import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const 宽度 = 512
const 高度 = 256
const 输出路径 = path.resolve(__dirname, '../public/env/studio.hdr')

const 底部色 = [0.02, 0.04, 0.08]
const 顶部色 = [0.18, 0.28, 0.42]
const 水平光色 = [0.06, 0.08, 0.12]

const 光斑列表 = [
  { u: 0.22, v: 0.78, 半径: 0.09, 颜色: [2.6, 1.7, 0.9], 强度: 5.0 },
  { u: 0.78, v: 0.74, 半径: 0.07, 颜色: [0.7, 2.3, 3.0], 强度: 4.0 },
  { u: 0.5, v: 0.9, 半径: 0.055, 颜色: [2.0, 1.1, 2.8], 强度: 3.5 },
  { u: 0.08, v: 0.55, 半径: 0.14, 颜色: [1.4, 1.7, 2.1], 强度: 1.4 },
  { u: 0.92, v: 0.52, 半径: 0.12, 颜色: [1.6, 1.5, 1.9], 强度: 1.2 },
]

function 获取像素颜色(u, v) {
  const 天顶因子 = Math.pow(1 - v, 1.55)
  const 基础R = 底部色[0] + (顶部色[0] - 底部色[0]) * 天顶因子
  const 基础G = 底部色[1] + (顶部色[1] - 底部色[1]) * 天顶因子
  const 基础B = 底部色[2] + (顶部色[2] - 底部色[2]) * 天顶因子

  const 水平因子 = Math.exp(-Math.pow((v - 0.36) / 0.1, 2))
  let r = 基础R + 水平光色[0] * 水平因子 * 0.45
  let g = 基础G + 水平光色[1] * 水平因子 * 0.45
  let b = 基础B + 水平光色[2] * 水平因子 * 0.45

  for (const 光斑 of 光斑列表) {
    const du = Math.min(Math.abs(u - 光斑.u), 1 - Math.abs(u - 光斑.u))
    const dv = v - 光斑.v
    const 距离 = Math.sqrt(du * du + dv * dv)
    const 衰减 = Math.exp(-Math.pow(距离 / 光斑.半径, 2))
    r += 光斑.颜色[0] * 衰减 * 光斑.强度
    g += 光斑.颜色[1] * 衰减 * 光斑.强度
    b += 光斑.颜色[2] * 衰减 * 光斑.强度
  }

  return [r, g, b]
}

function 编码RGBE(r, g, b) {
  const 最大值 = Math.max(r, g, b)
  if (最大值 < 1e-32) return [0, 0, 0, 0]
  const 指数 = Math.max(1, Math.min(254, Math.floor(Math.log2(最大值)) + 129))
  const 缩放 = Math.pow(2, 指数 - 128) / 256
  return [
    Math.min(255, Math.floor(r / 缩放)),
    Math.min(255, Math.floor(g / 缩放)),
    Math.min(255, Math.floor(b / 缩放)),
    指数,
  ]
}

function 编码通道RLE(通道值) {
  const 结果 = []
  let i = 0
  const 宽度 = 通道值.length
  while (i < 宽度) {
    let 连续长度 = 1
    while (i + 连续长度 < 宽度 && 通道值[i + 连续长度] === 通道值[i] && 连续长度 < 127) {
      连续长度++
    }
    if (连续长度 >= 4) {
      结果.push(128 + 连续长度, 通道值[i])
      i += 连续长度
      continue
    }

    let 字面长度 = 1
    while (i + 字面长度 < 宽度 && 字面长度 < 128) {
      let 后续连续 = 1
      while (
        i + 字面长度 + 后续连续 < 宽度 &&
        通道值[i + 字面长度 + 后续连续] === 通道值[i + 字面长度] &&
        后续连续 < 127
      ) {
        后续连续++
      }
      if (后续连续 >= 4) break
      字面长度++
    }

    结果.push(字面长度)
    for (let j = 0; j < 字面长度; j++) {
      结果.push(通道值[i + j])
    }
    i += 字面长度
  }
  return 结果
}

const 输出 = []

输出.push(
  ...Buffer.from('#?RADIANCE\n', 'ascii'),
  ...Buffer.from('# Generated by XuanRuiMuResume for FP-09\n', 'ascii'),
  ...Buffer.from('FORMAT=32-bit_rle_rgbe\n\n', 'ascii'),
  ...Buffer.from(`-Y ${高度} +X ${宽度}\n`, 'ascii')
)

for (let y = 0; y < 高度; y++) {
  const v = 1 - y / (高度 - 1)
  const r通道 = new Uint8Array(宽度)
  const g通道 = new Uint8Array(宽度)
  const b通道 = new Uint8Array(宽度)
  const e通道 = new Uint8Array(宽度)

  for (let x = 0; x < 宽度; x++) {
    const u = x / (宽度 - 1)
    const [r, g, b] = 获取像素颜色(u, v)
    const [rb, gb, bb, eb] = 编码RGBE(r, g, b)
    r通道[x] = rb
    g通道[x] = gb
    b通道[x] = bb
    e通道[x] = eb
  }

  输出.push(2, 2, (宽度 >> 8) & 0x7f, 宽度 & 0xff)
  输出.push(...编码通道RLE(r通道))
  输出.push(...编码通道RLE(g通道))
  输出.push(...编码通道RLE(b通道))
  输出.push(...编码通道RLE(e通道))
}

fs.mkdirSync(path.dirname(输出路径), { recursive: true })
fs.writeFileSync(输出路径, Buffer.from(输出))

const 文件大小 = fs.statSync(输出路径).size
console.log(`已生成 HDR 环境贴图: ${输出路径} (${(文件大小 / 1024).toFixed(1)} KB)`)
